require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PledgesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Pledge. As you add validations to Pledge, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PledgesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all pledges as @pledges" do
      pledge = Pledge.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:pledges)).to eq([pledge])
    end
  end

  describe "GET #show" do
    it "assigns the requested pledge as @pledge" do
      pledge = Pledge.create! valid_attributes
      get :show, {:id => pledge.to_param}, valid_session
      expect(assigns(:pledge)).to eq(pledge)
    end
  end

  describe "GET #new" do
    it "assigns a new pledge as @pledge" do
      get :new, {}, valid_session
      expect(assigns(:pledge)).to be_a_new(Pledge)
    end
  end

  describe "GET #edit" do
    it "assigns the requested pledge as @pledge" do
      pledge = Pledge.create! valid_attributes
      get :edit, {:id => pledge.to_param}, valid_session
      expect(assigns(:pledge)).to eq(pledge)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Pledge" do
        expect {
          post :create, {:pledge => valid_attributes}, valid_session
        }.to change(Pledge, :count).by(1)
      end

      it "assigns a newly created pledge as @pledge" do
        post :create, {:pledge => valid_attributes}, valid_session
        expect(assigns(:pledge)).to be_a(Pledge)
        expect(assigns(:pledge)).to be_persisted
      end

      it "redirects to the created pledge" do
        post :create, {:pledge => valid_attributes}, valid_session
        expect(response).to redirect_to(Pledge.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved pledge as @pledge" do
        post :create, {:pledge => invalid_attributes}, valid_session
        expect(assigns(:pledge)).to be_a_new(Pledge)
      end

      it "re-renders the 'new' template" do
        post :create, {:pledge => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pledge" do
        pledge = Pledge.create! valid_attributes
        put :update, {:id => pledge.to_param, :pledge => new_attributes}, valid_session
        pledge.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested pledge as @pledge" do
        pledge = Pledge.create! valid_attributes
        put :update, {:id => pledge.to_param, :pledge => valid_attributes}, valid_session
        expect(assigns(:pledge)).to eq(pledge)
      end

      it "redirects to the pledge" do
        pledge = Pledge.create! valid_attributes
        put :update, {:id => pledge.to_param, :pledge => valid_attributes}, valid_session
        expect(response).to redirect_to(pledge)
      end
    end

    context "with invalid params" do
      it "assigns the pledge as @pledge" do
        pledge = Pledge.create! valid_attributes
        put :update, {:id => pledge.to_param, :pledge => invalid_attributes}, valid_session
        expect(assigns(:pledge)).to eq(pledge)
      end

      it "re-renders the 'edit' template" do
        pledge = Pledge.create! valid_attributes
        put :update, {:id => pledge.to_param, :pledge => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested pledge" do
      pledge = Pledge.create! valid_attributes
      expect {
        delete :destroy, {:id => pledge.to_param}, valid_session
      }.to change(Pledge, :count).by(-1)
    end

    it "redirects to the pledges list" do
      pledge = Pledge.create! valid_attributes
      delete :destroy, {:id => pledge.to_param}, valid_session
      expect(response).to redirect_to(pledges_url)
    end
  end

end
